
 name: Scala CI

 on:
   push:
     branches: [ main ]

 jobs:
   build:

     runs-on: ubuntu-latest

     steps:
     - name: SonarCloud Scan
       run: sonar-scanner -Dproject.settings=../sonar-project.properties
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     - uses: actions/checkout@v2
     - name: Deployment
       uses: AkhileshNS/heroku-deploy@v3.8.8
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_email: ${{secrets.HEROKU_EMAIL}}
         heroku_app_name: ${{secrets.HEROKU_APP}}
